# |------------------------------------------------------------------------| #
# | #                                                                    # | #
# | #                -----------------------------------                 # | #
# | #                | CustomAnvils v${project.version} by xDec0de_ |                 # | #
# | #                -----------------------------------                 # | #
# | #                                                                    # | #
# |------------------------------------------------------------------------| #

repairCost:
  max: 40
  limit: -1
unsafeEnchants:
  allow: false
  upgrade:
    enabled: false
    limits:
    - "protection:10"
