# |------------------------------------------------------------------------| #
# | #                                                                    # | #
# | #                -----------------------------------                 # | #
# | #                | CustomAnvils v1.0.0 by xDec0de_ |                 # | #
# | #                -----------------------------------                 # | #
# | #                                                                    # | #
# |------------------------------------------------------------------------| #

repairCost:
  max: 40
  limit: -1
